name: Build Workflow

on:
  push:
    branches: master

jobs:
  build-windows:
    runs-on: windows-2019
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements_build.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller tdmgr.spec
      - uses: actions/upload-artifact@v2
        with:
          name: Windows_tdmgr
          path: dist/tdmgr_0.2.9.exe

  build-windows-x86:
    runs-on: windows-2019
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements_build.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller tdmgr32.spec
      - uses: actions/upload-artifact@v2
        with:
          name: Windows_tdmgr32
          path: dist/tdmgr_0.2.9_x86.exe

  build-ubuntu:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements_build.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller tdmgr.spec
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@v2
        with:
          name: Ubuntu
          path: dist/tdmgr_0.2.9


  build-macos:
    runs-on: macOS-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements_build.txt
          npm install --global create-dmg
      - name: Run PyInstaller
        run: |
          python -m PyInstaller tdmgr_mac.spec
      - name: See dist directory
        run: ls dist
      - name: Move app
        run: |
          #create-dmg dist/tdmgr_0.2.9.app
          #mv "tdmgr_0.2.9 0.0.0.dmg" dist/tdmgr_0.2.9.dmg
          mv dist/tdmgr_0.2.9.app dist/tdmgr_0.2.9-dev-macOS.app
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: dist/
